/*
 * Generated by Bluespec Compiler (build 7d25cde)
 * 
 * On Thu Aug 24 17:24:33 PDT 2023
 * 
 */
#ifndef __vpi_wrapper_bdpiAssertInterrupt_h__
#define __vpi_wrapper_bdpiAssertInterrupt_h__

#include <vpi_user.h>

/* registration function */
void bdpiAssertInterrupt_vpi_register();

/* VPI wrapper function */
PLI_INT32 bdpiAssertInterrupt_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_bdpiAssertInterrupt_h__ */
