/*
 * Generated by Bluespec Compiler (build 7d25cde)
 * 
 * On Thu Aug 24 17:24:33 PDT 2023
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_bdpiDmaReadData.h"
 *     void (*vlog_startup_routines[])() = { bdpiDmaReadData_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_bdpiDmaReadData call=bdpiDmaReadData_calltf size=32 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_bdpiDmaReadData vpiSysFuncSized 32 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
unsigned int bdpiDmaReadData();

/* VPI wrapper function */
PLI_INT32 bdpiDmaReadData_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  unsigned int vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 1u);
    handle_array[0u] = hCall;
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* call the imported C function */
  vpi_result = bdpiDmaReadData();
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_bdpiDmaReadData vpiSysFuncSized 32 unsigned */

/* tab: $imported_bdpiDmaReadData call=bdpiDmaReadData_calltf size=32 acc=rw:%TASK */

PLI_INT32 bdpiDmaReadData_sizetf(PLI_BYTE8 *user_data)
{
  return 32u;
}

/* VPI wrapper registration function */
void bdpiDmaReadData_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_bdpiDmaReadData";
  tf_data.calltf = bdpiDmaReadData_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = bdpiDmaReadData_sizetf;
  tf_data.user_data = "$imported_bdpiDmaReadData";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
