/*
 * Generated by Bluespec Compiler (build 7d25cde)
 * 
 * On Thu Aug 24 17:24:33 PDT 2023
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_bdpiDmaWriteData.h"
 *     void (*vlog_startup_routines[])() = { bdpiDmaWriteData_vpi_register, 0u };
 * 
 * For a Verilog simulator which requires a .tab file, use the following entry:
 * $imported_bdpiDmaWriteData call=bdpiDmaWriteData_calltf size=1 acc=rw:%TASK
 * 
 * For a Verilog simulator which requires a .sft file, use the following entry:
 * $imported_bdpiDmaWriteData vpiSysFuncSized 1 unsigned
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
char bdpiDmaWriteData(unsigned int , unsigned long long , unsigned long long );

/* VPI wrapper function */
PLI_INT32 bdpiDmaWriteData_calltf(PLI_BYTE8 *user_data)
{
  vpiHandle hCall;
  unsigned int arg_1;
  unsigned long long arg_2;
  unsigned long long arg_3;
  char vpi_result;
  vpiHandle *handle_array;
  
  /* retrieve handle array */
  hCall = vpi_handle(vpiSysTfCall, 0);
  handle_array = vpi_get_userdata(hCall);
  if (handle_array == NULL)
  {
    vpiHandle hArgList;
    hArgList = vpi_iterate(vpiArgument, hCall);
    handle_array = malloc(sizeof(vpiHandle) * 4u);
    handle_array[0u] = hCall;
    handle_array[1u] = vpi_scan(hArgList);
    handle_array[2u] = vpi_scan(hArgList);
    handle_array[3u] = vpi_scan(hArgList);
    vpi_put_userdata(hCall, handle_array);
    vpi_free_object(hArgList);
  }
  
  /* create return value */
  make_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* copy in argument values */
  get_vpi_arg(handle_array[1u], &arg_1, DIRECT);
  get_vpi_arg(handle_array[2u], &arg_2, DIRECT);
  get_vpi_arg(handle_array[3u], &arg_3, DIRECT);
  
  /* call the imported C function */
  vpi_result = bdpiDmaWriteData(arg_1, arg_2, arg_3);
  
  /* copy out return value */
  put_vpi_result(handle_array[0u], &vpi_result, DIRECT);
  
  /* free argument storage */
  free_vpi_args();
  vpi_free_object(hCall);
  
  return 0;
}

/* sft: $imported_bdpiDmaWriteData vpiSysFuncSized 1 unsigned */

/* tab: $imported_bdpiDmaWriteData call=bdpiDmaWriteData_calltf size=1 acc=rw:%TASK */

PLI_INT32 bdpiDmaWriteData_sizetf(PLI_BYTE8 *user_data)
{
  return 1u;
}

/* VPI wrapper registration function */
void bdpiDmaWriteData_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysFunc;
  tf_data.sysfunctype = vpiSizedFunc;
  tf_data.tfname = "$imported_bdpiDmaWriteData";
  tf_data.calltf = bdpiDmaWriteData_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = bdpiDmaWriteData_sizetf;
  tf_data.user_data = "$imported_bdpiDmaWriteData";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
