/*
 * Generated by Bluespec Compiler (build 7d25cde)
 * 
 * On Thu Aug 24 17:24:33 PDT 2023
 * 
 * To automatically register this VPI wrapper with a Verilog simulator use:
 *     #include "vpi_wrapper_bdpiAssertInterrupt.h"
 *     void (*vlog_startup_routines[])() = { bdpiAssertInterrupt_vpi_register, 0u };
 */
#include <stdlib.h>
#include <vpi_user.h>
#include "bdpi.h"

/* the type of the wrapped function */
void bdpiAssertInterrupt();

/* VPI wrapper function */
PLI_INT32 bdpiAssertInterrupt_calltf(PLI_BYTE8 *user_data)
{
  
  /* call the imported C function */
  bdpiAssertInterrupt();
  
  return 0;
}

/* VPI wrapper registration function */
void bdpiAssertInterrupt_vpi_register()
{
  s_vpi_systf_data tf_data;
  
  /* Fill in registration data */
  tf_data.type = vpiSysTask;
  tf_data.tfname = "$imported_bdpiAssertInterrupt";
  tf_data.calltf = bdpiAssertInterrupt_calltf;
  tf_data.compiletf = 0u;
  tf_data.sizetf = 0u;
  tf_data.user_data = "$imported_bdpiAssertInterrupt";
  
  /* Register the function with VPI */
  vpi_register_systf(&tf_data);
}
